spring.application.name=capstone-project

#local database
spring.datasource.url=jdbc:mysql://sh-cdb-atmrdmku.sql.tencentcdb.com:63928/capstone
spring.datasource.username=root
spring.datasource.password=Jason5038!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update


# application.properties
mybatis.mapper-locations=classpath*:mybatis/mapper/*.xml

#openai.api-key=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
openai.api-key=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
openai.api-url="https://api.openai.com/v1/chat/completions";